### ISSUE TITLE
MotherTode(`...`) doesn't always return a function

### ISSUE THREAD

**Issue by Magnogen** [TodePond/MotherTode#1] opened 2021-11-02 08:43 UTC
I wanted to get something working, so I copied your code at the end of README.md
![image](https://user-images.githubusercontent.com/25611707/139812204-fdfb5811-1a2b-42e3-a5a4-b6125a5ceccf.png)

That seemed to go semi-well, but it wasnt outputting anything - so I added in a `console.log(...)`. That was a bit finicky.
![image](https://user-images.githubusercontent.com/25611707/139812510-6de174cd-8035-4852-8364-eff23eb90303.png)

Then I decided to just copy the FizzBuzz language from https://l2wilson94.gitbook.io/mothertode/examples, but that didnt turn out very well either.
![image](https://user-images.githubusercontent.com/25611707/139813029-512cacf5-117a-4e25-83c1-5ee99eeafcb5.png)

Turns out `language` is actually an jumbled mess of otherwise empty arrays... (not all of them are expanded out here)
![image](https://user-images.githubusercontent.com/25611707/139813694-063203dc-f8ee-4aa1-b5a5-8081ffc6ca7b.png)

How do I actually use this tool?

**Comment by TodePond** [comment] 2021-11-02 12:38
I think the docs are a bit out of date and the codebase is in a very messy point at the moment. Thanks for raising the issue! I will have a look at it and do a cleanup :)

For example, I removed the `#` functionality from one of those examples, but haven't updated the docs to reflect the change (silly me).

The huge array object is the generated syntax tree, but there was some error with it, causing it to not work.

**Comment by TodePond** [comment] 2021-11-02 18:04
Ok I'm going to tackle this now. First thing to do is to split this up into smaller issues.

**Comment by TodePond** [comment] 2021-11-02 18:19
Ok, thank you again for trying out MotherTode and for submitting this issue! You have encountered this repo in a very early and messy state, so thank you for your patience :)

Thanks for helping me identify and find a bunch of issues to solve. I have split up some of the issues into smaller issues:

**Documentation**
A lot of the documentation is out of date and needs updating. And I think that 'hello world' example needs improving too.
#7 
#3 
#4 

**Error Logging**
MotherTode used to fill up the console with info about errors, which would have been helpful to you probably. I removed it as a quick fix because it was severely affecting performance, which was probably a very stupid idea. I need to put it back in!
#6 
#5

**Comment by TodePond** [comment] 2021-11-02 18:28
To answer your questions more specifically, the hello world example uses an old piece of syntax so doesn't work as intended. This would work better:
```js
const language = MotherTode(`:: /[a-zA-Z]/+ >> (name) => "Hello " + name + "!"`)
```
Then, you can use `language` as a function. All mothertode functions return a [result object](https://l2wilson94.gitbook.io/mothertode/result). So you can explicitly print the result like this:
```js
const language = MotherTode(`:: /[a-zA-Z]/+ >> (name) => "Hello " + name + "!"`)
const result = language("world")
console.log(result.output)
```

The FizzBuzz example isn't working for you because it doesn't have correct indentation. MotherTode uses your indents to figure out where your embedded code blocks start and end. You can fix it by doing this:
```js
const language = MotherTode(`

	:: FizzBuzz | Fizz | Buzz | Number
	Number :: /[0-9]/+ >> (n) => parseInt(n)
	FizzBuzz (
		:: Number
		?? (n) => n % 5 == 0 && n % 3 == 0
		>> "FizzBuzz"
	)

	Fizz (
		:: Number
		?? (n) => n % 3 == 0
		>> "Fizz"
	)

	Buzz (
		:: Number
		?? (n) => n % 5 == 0
		>> "Buzz"
	)

`)
```
And then use it by doing something like this:
```js
for (let i = 0; i < 20; i++) {
	const result = language(i.toString())
	console.log(result.output)
}
```

I hope that all helps! And thanks again for trying it out :)
I'll now close this issue because I've split everything into smaller ones. Please let me know if there's anything else I can help with, or if you find more issues ✨

**Closed as completed by TodePond** 2021-11-02 18:28 UTC
Labels: documentation, invalid, question

**Comment by Magnogen** [comment] 2021-11-02 20:35
Now this. This is the best answer to an issue I have ever raised in my _life._ I will follow your career with great interest.

Frogs rule! 🐸

**Comment by TodePond** [comment] 2021-11-02 20:39
Thanks very much! That's kind of you! I hope to fix some of those issues before December so that I can use MotherTode for Advent of Code again :)

**Comment by Magnogen** [comment] 2021-11-02 20:51
Nice! And perhaps you could make a more detailed video about it after! I'd be interested in seeing something like a tutorial in your style!

**Comment by TodePond** [comment] 2021-11-04 20:56
I would love to do that in the future!!! Possibly in early 2022 🤔 In the meantime, I'll try to fix these things up this weekend, and let me know if there's anything else you want to ask :)

**Comment by TodePond** [comment] 2021-11-07 13:55
I've started to fix up some of these issues now (see the other issues for more info). And the documentation is more updated now: https://l2wilson94.gitbook.io/mothertode/

By the way, here's another example of something I made with MotherTode if you want to see another example: https://github.com/l2wilson94/NumberTode

It was done with an older version so may/may not work, but should show you how some stuff works!

I also used it a lot last year for advent of code, and kind of made it alongside it. So it almost definitely doesn't work anymore, but you can check out more examples like this one: https://github.com/l2wilson94/AdventOfCode/blob/main/2020/day02.js

**Comment by Magnogen** [comment] 2021-11-07 16:22
Nice to see this project being made for a purpose, I sometimes see projects that people make and aren't used at all, it kinda bugs me 😅

**Comment by TodePond** [comment] 2021-11-07 22:02
Yes, most of what I make is to help me do things easier/quicker 😄
